### ISSUE TITLE
Server dead lock in FTB Chunks map shortly after a player joins

### ISSUE THREAD

**Issue by LemADEC** [FTBTeam/FTB-Omnia#66]
* **Modpack Version**: 1.3.0

* **Issue**:
Updated from 1.2.0 to 1.3.0, shortly after 2nd player connects, we both got timed out.
Server eventually crashed from the 300 s time out.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/d2a5c8c9

* **Is it Repeatable?**: yes, happens randomly when a player connects

* **Mod/s Affected**: FTB Chunks map feature is locked in the main server thread probably due to bad multi-threading in a non-identified mod.

* **Known Fix**: remove the FTB Chunks mod

**Comment by LatvianModder** [comment]
Odd, we've used FTB Chunks new update for couple days now and even after update had no issues.. For some reason it seems like just loading a chunk stops it.

**Comment by SirioIlBe** [comment]
i updated to 1.3 (singleplayer) and then went and killed the dragon.after i jumped into the portal an returned back to base everything is wainting for server. removed ftb chunks and now everything works. i had only 1 chunk chunkloaded

**Comment by LatvianModder** [comment]
Im rewriting the mod to be [almost] singleplayer only. So much for wanting an unique feature, like ally shared maps :p

**Comment by LatvianModder** [comment]
I have removed FTB Chunks from my server, and it still starts lagging horribly after couple hours. I think there is something else messing with chunks. Even got a crash similar to this, but it was different mod calling it instead

**Comment by MaxFerney** [comment]
[crash-reports.zip](https://github.com/FTBTeam/FTB-Omnia/files/4618134/crash-reports.zip)
Also having a similar issue, however two players went into the Dream dimension (from good night sleep) one into good dream, one into bad dream, and when they came out, both crashed the server with them joining. any time they joined, the server would instantly crash

Only fix so far was we deleted the players data and gave them back stuff from not dream dimension. it only happened in 1.3.0 so far, and only repeatable on server. I still have server logs from when it crashed but posting here because the logs mentioned ftb chunks failed

**Comment by Sunekaer** [comment]
@MaxFerney 
Please use https://paste.feed-the-beast.com/ for logs

**Comment by Ratomas** [comment]
If MaxFerney is right then my issue is related to this also [#72](https://github.com/FTBTeam/FTB-Omnia/issues/72)

**Comment by Sunekaer** [comment]
@LemADEC is this still an issue with a newer version of the pack? if so please reopen the issue
